# Environment Config - please use _ and not .

# Store your secrets and config variables in here
# only invited collaborators will be able to see your .env values
# reference these in your code with process.env.SECRET

verifiability=verifiability
LEARNING_MODE=false
